[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_BACK_END_SERVER_URL"  # Add this line
  GO_VERSION = "1.19.13"  
  NODE_VERSION = "20"     



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
