[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_BACK_END_SERVER_URL = "http://mycryptohaven.com"
SECRETS_SCAN_OMIT_KEYS = "VITE_BACK_END_SERVER_URL"

[secrets]
  omit_keys = ["VITE_BACK_END_SERVER_URL"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
